# Generated by Django 3.1.2 on 2020-11-30 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='reason',
        ),
        migrations.AddField(
            model_name='post',
            name='dream_holiday',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='world.worldborder'),
        ),
    ]
